src/src/SeerUK/DWright/GalleryBundle/Entity/Gallery.php
<?php

/**
 * Gallery Entity
 *
 * Acts as a container for a single gallery
 *
 * @package    DWright
 * @subpackage GalleryBundle
 */

namespace SeerUK\DWright\GalleryBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Gallery
 *
 * @ORM\Table(name="Gallery")
 * @ORM\Entity(repositoryClass="SeerUK\DWright\GalleryBundle\Entity\GalleryRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Gallery
{
    /**
     * @ORM\Id
     * @ORM\Column(name="intGalleryId", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;


    /**
     * @Assert\NotBlank()
     * @ORM\Column(name="strGalleryName", type="string", length=50)
     */
    protected $name;


    /**
     * @Assert\NotBlank()
     * @ORM\Column(name="strGalleryDesc", type="string", length=5000)
     */
    protected $desc;


    /**
     * @ORM\Column(name="dtmPublished", type="datetime")
     */
    protected $posted;


    /**
     * @ORM\OneToMany(targetEntity="GalleryImage", mappedBy="gallery")
     */
    protected $galleryImages;


    /**
     * Constructor
     */
    public function __construct()
    {
        $this->galleryImages = new \Doctrine\Common\Collections\ArrayCollection();
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }


    /**
     * Get desc
     *
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }


    /**
     * Get posted
     *
     * @return string
     */
    public function getPosted()
    {
        return $this->posted;
    }


    /**
     * Set name
     *
     * @param string $name
     * @return Gallery
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }


    /**
     * Set desc
     *
     * @param string $desc
     * @return Gallery
     */
    public function setDesc($desc)
    {
        $this->desc = $desc;

        return $this;
    }


    /**
     * Set posted
     *
     * @param \DateTime $posted
     * @return Gallery
     */
    public function setPosted(\DateTime $posted)
    {
        $this->posted = $posted;

        return $this;
    }


    /**
     * @ORM\PrePersist
     */
    public function setPostedOnCreation()
    {
        $this->posted = new \DateTime();

        return $this;
    }


    /**
     * Add galleryImages
     *
     * @param \SeerUK\DWright\GalleryBundle\Entity\GalleryImage $galleryImages
     * @return Gallery
     */
    public function addGalleryImage(\SeerUK\DWright\GalleryBundle\Entity\GalleryImage $galleryImages)
    {
        $this->galleryImages[] = $galleryImages;

        return $this;
    }


    /**
     * Remove galleryImages
     *
     * @param \SeerUK\DWright\GalleryBundle\Entity\GalleryImage $galleryImages
     */
    public function removeGalleryImage(\SeerUK\DWright\GalleryBundle\Entity\GalleryImage $galleryImages)
    {
        $this->galleryImages->removeElement($galleryImages);
    }


    /**
     * Get galleryImages
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGalleryImages()
    {
        return $this->galleryImages;
    }
}

src/src/SeerUK/DWright/GalleryBundle/Entity/GalleryImage.php
<?php

namespace SeerUK\DWright\GalleryBundle\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * Gallery
 *
 * @ORM\Table(name="GalleryImage")
 * @ORM\Entity
 */
class GalleryImage
{
    /**
     * @ORM\Id
     * @ORM\Column(name="intGalleryImageId", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;


    /**
     * @ORM\Column(name="strGalleryImageName", type="string", length=50)
     */
    protected $name;


    /**
     * @ORM\Column(name="strGalleryImageDesc", type="string", length=255)
     */
    protected $desc;


    /**
     * @ORM\Column(name="intGalleryId", type="integer")
     */
    protected $galleryId;


    /**
     * @ORM\Column(name="strPath", type="string")
     */
    protected $path;


    /**
     * @ORM\Column(name="dtmPublished", type="datetime")
     */
    protected $posted;


    /**
     * @ORM\ManyToOne(targetEntity="Gallery", inversedBy="galleryImages")
     * @ORM\JoinColumn(name="intGalleryId", referencedColumnName="intGalleryId")
     */
    protected $gallery;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }


    /**
     * Get desc
     *
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }


    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }


    /**
     * Get publishedOn
     *
     * @return string
     */
    public function getPosted()
    {
        return $this->posted;
    }


    /**
     * Get galleryId
     *
     * @return integer
     */
    public function getGalleryId()
    {
        return $this->galleryId;
    }


    /**
     * Get gallery
     *
     * @return \SeerUK\DWright\GalleryBundle\Entity\Gallery
     */
    public function getGallery()
    {
        return $this->gallery;
    }


    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir() . '/' . $this->path;
    }


    public function getAbsoluteThumbPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir() . '/thumbs/' . $this->path;
    }


    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir() . '/' . $this->path;
    }


    public function getWebThumbPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir() . '/thumbs/' . $this->path;
    }


    protected function getUploadRootDir()
    {
        return __DIR__ . '/../../../../../web/' . $this->getUploadDir();
    }


    protected function getUploadDir()
    {
        return 'bundles/seerukdwrightgallery/upload/gallery/' . $this->galleryId;
    }


    /**
     * Set name
     *
     * @param string $name
     * @return GalleryImage
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }


    /**
     * Set desc
     *
     * @param string $desc
     * @return GalleryImage
     */
    public function setDesc($desc)
    {
        $this->desc = $desc;

        return $this;
    }


    /**
     * Set publishedOn
     *
     * @param \DateTime $publishedOn
     * @return GalleryImage
     */
    public function setPosted($posted)
    {
        $this->posted = $posted;

        return $this;
    }


    /**
     * Set galleryId
     *
     * @param integer $galleryId
     * @return GalleryImage
     */
    public function setGalleryId($galleryId)
    {
        $this->galleryId = $galleryId;

        return $this;
    }


    /**
     * Set path
     *
     * @param string $path
     * @return GalleryImage
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }


    /**
     * Set gallery
     *
     * @param \SeerUK\DWright\GalleryBundle\Entity\Gallery $gallery
     * @return GalleryImage
     */
    public function setGallery(\SeerUK\DWright\GalleryBundle\Entity\Gallery $gallery = null)
    {
        $this->gallery = $gallery;

        return $this;
    }
}

src/src/SeerUK/DWright/GalleryBundle/Form/Type/GalleryType.php
<?php

/*
 * This file is part of the SeerUKDwrightGalleryBundle
 *
 * (c) Elliot Wright <wright.elliot@gmail.com> - 2013
 *
 * For full license information please visit
 * http://license.visualidiot.com/
 */

namespace SeerUK\DWright\GalleryBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Gallery Type
 */
class GalleryType extends AbstractType
{
    /**
     * Builds the form ...
     *
     * @param  FormBuilderInterface $builder
     * @param  array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', 'text', array('label' => 'Title'));
        $builder->add('desc', 'textarea', array('label' => 'Description'));
    }


    /**
     * Sets default options
     *
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SeerUK\DWright\GalleryBundle\Entity\Gallery',
        ));
    }


    /**
     * Gets name ...
     *
     * @return string
     */
    public function getName()
    {
        return 'gallery';
    }
}

src/src/SeerUK/DWright/GalleryBundle/Controller/GalleryController.php
<?php

/*
 * This file is part of the SeerUKDwrightGalleryBundle
 *
 * (c) Elliot Wright <wright.elliot@gmail.com> - 2013
 *
 * For full license information please visit
 * http://license.visualidiot.com/
 */

namespace SeerUK\DWright\GalleryBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

/**
 * Gallery Controller
 */
class GalleryController extends Controller
{
    /**
     * Shows a gallery category, the galleries within and the cover images
     * of said galleries.
     *
     * @param  integer $categoryId
     * @return object
     */
    public function galleryHomeAction()
    {
        $galleryHelper = $this->get('seer_ukd_wright_gallery.gallery_helper');

        return $this->render('SeerUKDWrightGalleryBundle:Gallery:home.html.twig', array(
            'galleries' => $galleryHelper->getPaginatedHomeView()
        ));
    }


    /**
     * Shows a gallery, and the images within.
     *
     * @param  integer $galleryId
     * @return object
     */
    public function galleryAction($galleryId)
    {
        $galleryHelper = $this->get('seer_ukd_wright_gallery.gallery_helper');

        return $this->render('SeerUKDWrightGalleryBundle:Gallery:gallery.html.twig', array(
            'gallery' => $galleryHelper->getPaginatedGalleryView($galleryId)
        ));
    }
}

src/src/SeerUK/DWright/GalleryBundle/Resources/views/Gallery/category.html.twig
{##
 #  Page metadata
 #}
{% extends '::master.html.twig' %}

{% block stylesheets %}
    {% include 'SeerUKDWrightGalleryBundle:Generic:stylesheets.html.twig' %}
{% endblock %}

{% block javascripts %}
    {% include 'SeerUKDWrightGalleryBundle:Generic:javascripts.html.twig' %}
{% endblock %}

{% block title %}{{ category.name }}{% endblock %}


{##
 #  Page content
 #}
{% block body %}

    <div class="hero-unit">
        <h1>{{ category.name }}</h1>
        <small>{{ category.desc }}</small>
    </div>

    <div class="content">
        <div class="content-category">

            {% if category.galleries|length %}

                <ul class="clearfix thumbnails">

                    {% for gallery in category.galleries %}

                        <li>
                            <div>
                                <div class="overlay">
                                    <a class="" href="{{ url('seer_ukd_wright_gallery_gallery_short', { 'galleryId': gallery.id }) }}"></a>
                                    <h3 class="entry-title">{{ gallery.name }}</h3>
                                    <p class="posted"><span class="emp">{{ gallery.posted|relativeDateTime }}</span></p>
                                </div>

                                {% if gallery.galleryImages|length %}

                                    <img src="{{ asset(gallery.galleryImages[0].webThumbPath) }}" alt="" title="" />

                                {% else %}

                                    <img src="{{ asset('http://placebacn.com/400/400') }}" alt="" title="" />

                                {% endif %}

                            </div>
                        </li>

                    {% endfor %}

                </ul>

            {% endif %}

        </div>
    </div>

{% endblock %}

src/src/SeerUK/DWright/GalleryBundle/Resources/views/Gallery/gallery.html.twig
{##
 #  Page metadata
 #}
{% extends '::master.html.twig' %}

{% block stylesheets %}
    {% include 'SeerUKDWrightGalleryBundle:Generic:stylesheets.html.twig' %}
{% endblock %}

{% block javascripts %}
    {% include 'SeerUKDWrightGalleryBundle:Generic:javascripts.html.twig' %}
{% endblock %}

{% block title %}{{ gallery.name }}{% endblock %}


{##
 #  Page content
 #}
{% block body %}

    <div class="hero-unit">
        <h1>{{ gallery.name }}</h1>
        <small>Possible gallery sub-title, this should probably be an optional feature...</small>
    </div>

    <div class="content">
        <div class="content-desc">
            {# Content here should be in paragraphs... #}
            {{ gallery.desc|raw }}

            <p><small class="muted">PUBLISHED</small><br />{{ gallery.posted|relativeDateTime }}</p>
            <p><small class="muted">NUMBER OF IMAGES</small><br />{{ gallery.galleryImages|length }}</p>
        </div>
        <div class="content-gallery">

            {% if gallery.galleryImages|length %}

                <ul class="clearfix thumbnails">

                    {% for galleryImage in gallery.galleryImages %}

                        <li>
                            <a href="{{ asset(galleryImage.webPath) }}" class="view" rel="adventure">
                                <img src="{{ asset(galleryImage.webPath) }}" alt="" title="" />
                            </a>
                        </li>

                    {% endfor %}

                </ul>

            {% else %}

                <div class="content text-center">
                    <h1>There are no images in this gallery.</h1>
                </div>

            {% endif %}

        </div>
    </div>

{% endblock %}

src/src/SeerUK/DWright/GalleryBundle/Resources/views/Gallery/home.html.twig
{##
 #  Page metadata
 #}
{% extends '::master.html.twig' %}

{% block stylesheets %}
    {% include 'SeerUKDWrightGalleryBundle:Generic:stylesheets.html.twig' %}
{% endblock %}

{% block javascripts %}
    {% include 'SeerUKDWrightGalleryBundle:Generic:javascripts.html.twig' %}
{% endblock %}

{% block title %}Portfolio{% endblock %}


{##
 #  Page content
 #}
{% block body %}

    <div class="hero-unit">
        <h1>Portfolio</h1>
        <small>Some tagline for my galleries</small>
    </div>

    <div class="content">
        <div class="content-category">

            {% if galleries|length %}

                <ul class="clearfix thumbnails">

                    {% for gallery in galleries %}


                            <li>
                                <div>
                                    <div class="overlay">
                                        <a class="" href="{{ url('seer_ukd_wright_gallery_gallery_short', { 'galleryId': gallery.id }) }}"></a>
                                        <h3 class="entry-title">{{ gallery.name }}</h3>
                                        <p class="posted"><span class="emp">{{ gallery.posted|relativeDateTime }}</span></p>
                                    </div>

                                    {% if gallery.galleryImages|length %}
                                        <img src="{{ asset(gallery.galleryImages[0].webThumbPath) }}" alt="" title="" />
                                    {% else %}
                                        <img src="{{ asset('http://placehold.it/300x300') }}" alt="" title="" />
                                    {% endif %}

                                </div>
                            </li>


                    {% endfor %}

                </ul>

            {% else %}

                <p class="text-center">There are currently no galleries.</p>

            {% endif %}

        </div>
    </div>

{% endblock %}

src/src/SeerUK/DWright/GalleryBundle/Resources/views/Gallery/index.html.twig
<!-- <strong>Gallery {{ galleryId }}'s</strong> name is: {{ galleryName }}! -->


<h1>{{ galleryName }} ({{ galleryId }})</h1>
<p>{{ galleryDesc }}</p>
<p>{{ galleryPublishedOn }} </p>